# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/labs/cordic-finalversion/cordic-finalversion.cache/wt [current_project]
set_property parent.project_path Z:/labs/cordic-finalversion/cordic-finalversion.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  Z:/labs/cordic-new/cordic-new.srcs/sources_1/new/hexto7seg.v
  Z:/labs/cordic-new/cordic-new.srcs/sources_1/imports/cordic/cordic.v
  Z:/labs/cordic-new/cordic-new.srcs/sources_1/new/lab8_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/labs/cordic-new/cordic-new.srcs/constrs_1/new/lab8.xdc
set_property used_in_implementation false [get_files Z:/labs/cordic-new/cordic-new.srcs/constrs_1/new/lab8.xdc]


synth_design -top lab8_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab8_top.dcp

catch { report_utilization -file lab8_top_utilization_synth.rpt -pb lab8_top_utilization_synth.pb }
